export default {
  TAB_FEED: 'https://www.douyin.com/aweme/v1/web/tab/feed/?',
  USER_SHORT_INFO: 'https://www.douyin.com/aweme/v1/web/im/user/info/?',
  USER_DETAIL: 'https://www.douyin.com/aweme/v1/web/user/profile/other/?',
  BASE_AWEME: 'https://www.douyin.com/aweme/v1/web/aweme/',
  USER_POST: 'https://www.douyin.com/aweme/v1/web/aweme/post/?',
  POST_DETAIL: 'https://www.douyin.com/aweme/v1/web/aweme/detail/?',
  USER_FAVORITE_A: 'https://www.douyin.com/aweme/v1/web/aweme/favorite/?',
  USER_FAVORITE_B: 'https://www.iesdouyin.com/web/api/v2/aweme/like/?',
  USER_HISTORY: 'https://www.douyin.com/aweme/v1/web/history/read/?',
  USER_COLLECTION: 'https://www.douyin.com/aweme/v1/web/aweme/listcollection/?',
  COMMENT: 'https://www.douyin.com/aweme/v1/web/comment/list/?',
  FRIEND_FEED: 'https://www.douyin.com/aweme/v1/web/familiar/feed/?',
  FOLLOW_FEED: 'https://www.douyin.com/aweme/v1/web/follow/feed/?',
  RELATED: 'https://www.douyin.com/aweme/v1/web/aweme/related/?',
  LIVE: 'https://live.douyin.com/webcast/room/web/enter/?',
  SSO_LOGIN_GET_QR: 'https://sso.douyin.com/get_qrcode/?',
  SSO_LOGIN_CHECK_QR: 'https://sso.douyin.com/check_qrconnect/?',
  SSO_LOGIN_CHECK_LOGIN: 'https://sso.douyin.com/check_login/?',
  SSO_LOGIN_REDIRECT: 'https://www.douyin.com/login/?',
  SSO_LOGIN_CALLBACK: 'https://www.douyin.com/passport/sso/login/callback/?',
  POST_COMMENT: 'https://www.douyin.com/aweme/v1/web/comment/list/?',
  POST_COMMENT_PUBLISH: 'https://www.douyin.com/aweme/v1/web/comment/publish?',
  POST_COMMENT_DELETE: 'https://www.douyin.com/aweme/v1/web/comment/delete/?',
  POST_COMMENT_DIGG: 'https://www.douyin.com/aweme/v1/web/comment/digg?',
  POST_COMMENT_REPLY: 'https://www.douyin.com/aweme/v1/web/comment/list/reply/?',
  NOTICE: 'https://www.douyin.com/aweme/v1/web/notice/?'
  // GET_XB_PATH: 'http://127.0.0.1:8889/xg/path?url=',
  // GET_XB_LOGIN: 'http://47.115.200.238/login',
  // GET_XB_REGISTER: 'http://47.115.200.238/register',
  // GET_XB_TOKEN: 'http://47.115.200.238/token',
  // GET_XG_LOGIN: 'http://47.115.200.238/xog/path?url=',
}
